// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZ0J9zwyUwdGaSM8ALipJNca9IDLdGbcE',
    appId: '1:624499135514:web:3db10f6037443bc8ebeda3',
    messagingSenderId: '624499135514',
    projectId: 'cookcaquiz',
    authDomain: 'cookcaquiz.firebaseapp.com',
    storageBucket: 'cookcaquiz.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOKYhAki1htJR38EKY87pgFRbnbSFM6BU',
    appId: '1:624499135514:android:35f3a604909e1518ebeda3',
    messagingSenderId: '624499135514',
    projectId: 'cookcaquiz',
    storageBucket: 'cookcaquiz.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHMAFz3ETwpF0f87_y7y2wBKgLOwqt03w',
    appId: '1:624499135514:ios:921efc3320e216ecebeda3',
    messagingSenderId: '624499135514',
    projectId: 'cookcaquiz',
    storageBucket: 'cookcaquiz.appspot.com',
    iosClientId: '624499135514-925h9tqqtg1fl9grrk5qq1lj31ebqfmj.apps.googleusercontent.com',
    iosBundleId: 'com.quizlen.quizlen',
  );
}
